export { ReactComponent as BrushIcon } from "./brush.svg";
export { ReactComponent as CircleIcon } from "./circle.svg";
export { ReactComponent as EraserIcon } from "./eraser.svg";
export { ReactComponent as LineIcon } from "./line.svg";
export { ReactComponent as RectIcon } from "./rect.svg";
export { ReactComponent as RedoIcon } from "./redo.svg";
export { ReactComponent as SaveIcon } from "./save.svg";
export { ReactComponent as UndoIcon } from "./undo.svg";
export { ReactComponent as PaletteIcon } from "./palette.svg";
